### ISSUE TITLE
explore `sqrt` correctness/efficiency

### ISSUE THREAD

**Issue by NoahZinsmeister** [Uniswap/v3-core#123]
our desired `sqrt` implementation should satisfy: `computed_result = floor(true_result)`

the current implementation of `sqrt`:

- may not have this property because of a possible issue with the proof (TBD - https://github.com/Uniswap/uniswap-lib/issues/25)
- there is another candidate implementation which seems to be much cheaper (https://github.com/Uniswap/uniswap-lib/pull/23), but may not have our desired property
- it's _possible_ that we might want 512-bit support, to ameliorate rounding errors. something like `mulRoot` (analogous to [`mulDiv`](https://github.com/Uniswap/uniswap-lib/blob/master/contracts/libraries/FullMath.sol#L35)) may be worth exploring (see e.g. [where `sqrt` is used in the current code](https://github.com/Uniswap/uniswap-v3-core/blob/master/contracts/libraries/PriceMath.sol#L46))

**Comment by fariborz4** [comment]
Ok
