### ISSUE TITLE
separate protocol fee for token0 and token1

### ISSUE THREAD

**Issue by moodysalem** [Uniswap/v3-core#383]
gives it a reason to be a denominator rather than a percentage, since it’ll be 2 uint4s that are lt 16
allows protocol to collect fees on sketch tokens paired w eth/real tokens

**Comment by greyyT** [comment]
I appreciate your work. I'm currently studying about uniswap, but is there by any chance can you explain to me why you have to separate protocol fee for each token. Because the previous approach when there is only one protocol fee is easier to understand. Thank you.
