### ISSUE TITLE
Contract creation initialization returns data with length of more than 24576 bytes. The deployment will likely fails.

### ISSUE THREAD

**Issue by Jackie-Zhong** [Uniswap/v3-core#497]
when I try to use remix to deploy the Factory contract,but it faild.of course i have opened the optiminzation. Is this an official design on purpuse? if not,how to solve this?

**Comment by moodysalem** [comment]
It obviously doesn't fail or exceed 24576 bytes since it is deployed. We have a unit test to that effect: https://github.com/Uniswap/v3-core/blob/c05a0e2c8c08c460fb4d05cfdda30b3ad8deeaac/test/__snapshots__/UniswapV3Factory.spec.ts.snap#L5
