### ISSUE TITLE
Get Token spot price

### ISSUE THREAD

**Issue by heeropunjabi** [Uniswap/v3-core#511]
Hi Team, 
thanks for the great work done on Uniswap.

I was going through the docs at https://docs.uniswap.org/protocol/V2/reference/smart-contracts.
since these contracts are used by https://quickswap.exchange/

I am looking for a better solution where I can get a spot price for a pair.
I came across this https://docs.uniswap.org/protocol/V2/reference/smart-contracts/pair#swap

Event will be triggered as soon as swap will happen at uniswap.

Our code will continuously listen for events on that pair and as swap happens we will calculate the spot price.

As there any better approach for the given problem?
TIA

**Comment by NoahZinsmeister** [comment]
sorry @heeropunjabi , this is not the appropriate repo for that question. you may have better luck in the discord
