### ISSUE TITLE
What is the meaning of 'exactIn'?

### ISSUE THREAD

**Issue by chaufinhay** [Uniswap/v3-core#535]
From my understanding, the boolean flag `exactIn` is to track whether we want to add or withdraw amount from the pool. However why the variable is named `exactIn` (or `exactInput`, depends on which file we look at)?

**Comment by 7779043** [comment]
https://github.com/Uniswap/v3-core/issues/535#issue-1123767683

**Comment by 7779043** [comment]
https://github.com/Uniswap/v3-core/issues/535#issue-1123767683

**Comment by NoahZinsmeister** [comment]
`exactIn` refers to an specific input amount being swapped for as much output as possible, as opposed to as little input as possible for a specific output amount
