### ISSUE TITLE
can't sell token with custom fee on transfer

### ISSUE THREAD

**Issue by antonina-nesmelova** [Uniswap/v3-core#555]
I'm developing token on polygon with fees on sell and buy, on uniswap v3 buy is working well, but sell throw error "execution reverted: IIA". On quickswap, fork of uniswap v2, buy and sell works fine, but i want better to have pair on uniswap. Please help.

**Comment by marktoda** [comment]
Hi @antonina-nesmelova - thanks for reporting this issue. Fee-on-transfer tokens aren't supported by UniswapV3 - more information in this doc: https://docs.uniswap.org/protocol/concepts/advanced/integration-issues#fee-on-transfer-tokens
