### ISSUE TITLE
Implement token ERC223 for swap and liquidity pools

### ISSUE THREAD

**Issue by laurent387** [Uniswap/v3-core#566]
Hello
Implement token ERC223 for swap and liquidity pools please
Bounty : 5000 [SaTT](https://www.satt.io/)
Thanks

**Comment by geoffreymoya** [comment]
the right solidity function is : tokenFallback(address,uint,bytes32 ) pure public
it must be implemented by contract that operate transferFrom()

**Comment by marktoda** [comment]
Hi @laurent387 - thanks for submitting this request. We won't be able to add this as the Uniswap V3 contracts are immutable and can't be upgraded with new features. We prefer to keep the main codebase on GitHub aligned with the code deployed to the blockchain.
