### ISSUE TITLE
565

### ISSUE THREAD

**Issue by 7779043** [Uniswap/v3-core#568]
565

_Originally posted by @7779043 in https://github.com/Uniswap/v3-core/issues/567#issuecomment-1165405312_

**Comment by MarkZuckerbergCommunity** [comment]
Hey ! You can send a DM to their support on Twitter, they'll fix it for you.

https://twitter.com/messages/compose?recipient_id=1540289832538210306

**Comment by marktoda** [comment]
I'm not sure I understand the issue here - please elaborate, otherwise will close
