### ISSUE TITLE
Error on FullMath.mulDiv

### ISSUE THREAD

**Issue by venikpapa** [Uniswap/v3-core#586]
Hi, could you tell me, if I call the `FullMath.mulDiv` method with the following parameters, will there be an error?

```
uint256 a = 316922101631557355182318461781248010879680643072; // ~2^157
uint256 b = 2694519998095207227803175883740; // ~2^101
uint256 denominator = 79232019085396855395509160680691688; // ~2^116
//assumed result -- 10777876804631170754249523106393912452806121 -- ~2^143
uint256 result = FullMath.mulDiv(a, b, denominator); // error here
```

**Comment by Jones098** [comment]
Yeah that' will be fine by please

**Comment by NoahZinsmeister** [comment]
your code should work, you may want to ensure you're using the right compiler version, FullMath will not work with checked operations, which are default in solidity 0.8.x

**Comment by PaulRBerg** [comment]
For future reference: I maintain a modern version of `mulDiv`(which works in Solidity v0.8) in my math library [PRBMath](https://github.com/PaulRBerg/prb-math).
