### ISSUE TITLE
getAmountsOut on v3 stop working

### ISSUE THREAD

**Issue by ubuntutest** [Uniswap/v3-core#592]
this is the complete code I use on my Dapp, it worked until this morning for both routerv3 and routerv2, now it has stopped working.

`getAmountsOut()` doesn't seem to work with v3, I've searched the web, can't find anything related to v3, but how has it worked so far?
I can't trace the cause.

```
import ethers from 'ethers';
import { WebSocketProvider } from './assets/ts/webSocket.js';

const ROUTER_ADDRESS = '0xE592427A0AEce92De3Edee1F18E0157C05861564'; //ROUTER V3 
//const ROUTER_ADDRESS = '0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D'; //ROUTER V2 - working

var PrivateKey = new ethers.Wallet("PRIVATE_KEY");
var provider = new WebSocketProvider('wss://goerli.infura.io/ws/v3/APY_KEY');
var account = PrivateKey.connect(provider);

var router = new ethers.Contract(
    ROUTER_ADDRESS,
    [
        `function getAmountsOut(uint amountIn, address[] memory path) public view returns (uint[] memory amounts)`,
    ],
    account
);

const main = async () => {
    try {
        var amountCheckLiq = ethers.utils.parseUnits('0.01');
        var amountOutMin = await router.getAmountsOut(amountCheckLiq, ["0xCc7bb2D219A0FC08033E130629C2B854b7bA9195", "0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6"]);
        amountOutMin = amountOutMin[1];
        amountOutMin = ethers.utils.formatEther(amountOutMin)
        console.log("amountOutMin: " + amountOutMin)
    } catch (error) {
        console.log(error)
    }
}
main()

```

**Comment by DuhCompuder** [comment]
What's your error message?

**Comment by Jones098** [comment]
Good

**Comment by Jones098** [comment]
Good

**Comment by ubuntutest** [comment]
@DuhCompuder 
This is the error:
`reason: 'missing revert data in call exception; Transaction reverted without a reason string ',`

For a few hours I used it correctly in production, but from what I understand `getAmountsOut` is no longer usable in V3, I wonder how it is possible that I have used it, maybe a bug?

**Comment by M9na12** [comment]
Need help

**Comment by NoahZinsmeister** [comment]
exact input or output amounts may be requested in v3 by specifying positive or negative amounts. you may reference https://github.com/Uniswap/swap-router-contracts for examples

**Comment by ubuntutest** [comment]
@NoahZinsmeister i have already tried unsuccessfully, i will try again.
The ultimate goal is to get the best price if it is v2 or v3 and then carry out the swap
