### ISSUE TITLE
auto route working example

### ISSUE THREAD

**Issue by ubuntutest** [Uniswap/v3-core#593]
is it possible to get a working example of the autoroute? the one in the [documentation](https://docs.uniswap.org/sdk/guides/auto-router) is missing many parameters and imports, such as:
```
ChainID.MAINNET
JSBI
currency
BigNumber 
..
```
And a lot more.
thanks

**Comment by NoahZinsmeister** [comment]
this is not the appropriate venue for your question, https://docs.uniswap.org/ may have some useful information

**Comment by ubuntutest** [comment]
The wrong and missing information is right here https://docs.uniswap.org/.
If I can't ask on github, where will I ever be able to?
