### ISSUE TITLE
Fix getFeeGrowthInside function bug?

### ISSUE THREAD

**Issue by jingkang0822** [Uniswap/v3-core#646]
Are these two lines should be + feeGrowthBelow instead of - feeGrowthBelow?

feeGrowthInside0X128 = feeGrowthGlobal0X128 + feeGrowthBelow0X128 - feeGrowthAbove0X128;
feeGrowthInside1X128 = feeGrowthGlobal1X128 + feeGrowthBelow1X128 - feeGrowthAbove1X128;

**Comment by Abeanna** [comment]
Yes

**Comment by jingkang0822** [comment]
It is very strage:
1. Some time these formular will underflow.
2. feeGrowthBelow0X128 will increase as feeGrowthAbove0X128, this behaviour will make feeGrowthBelow0X128 more like feeGrowthAboveLower0X128.

 But According to some discussion, it should be - feeGrowthBelow0X128 - feeGrowthAbove0X128.
 https://github.com/Jeiwan/uniswapv3-book/issues/45
